// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'tu-api-key',
    appId: 'tu-app-id',
    messagingSenderId: 'tu-messaging-sender-id',
    projectId: 'tu-project-id',
    authDomain: 'tu-auth-domain',
    storageBucket: 'tu-storage-bucket',
    measurementId: 'tu-measurement-id',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'tu-api-key',
    appId: 'tu-app-id',
    messagingSenderId: 'tu-messaging-sender-id',
    projectId: 'tu-project-id',
    storageBucket: 'tu-storage-bucket',
    iosBundleId: 'tu-ios-bundle-id',
  );
  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'tu-api-key',
  //   appId: 'tu-app-id',
  //   messagingSenderId: 'tu-messaging-sender-id',
  //   projectId: 'tu-project-id',
  //   authDomain: 'tu-auth-domain',
  //   storageBucket: 'tu-storage-bucket',
  //   measurementId: 'tu-measurement-id',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'tu-api-key',
  //   appId: 'tu-app-id',
  //   messagingSenderId: 'tu-messaging-sender-id',
  //   projectId: 'tu-project-id',
  //   storageBucket: 'tu-storage-bucket',
  //   iosBundleId: 'com.example.voiceFlutter',
  // );
}
